name: Pull Request Validation

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, edited, synchronize, reopened]

  workflow_dispatch:

env:
  NEXT_PUBLIC_SENTRY_ENVIRONMENT: test

jobs:
  validate:
    name: Validate PR Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enforce Pull Request Description Length
        uses: ryanvade/enforce-pr-description-length-action@v1
        with:
          minLength: 5

  run-tests:
    name: Run Frontend Test Suite
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: yarn install

      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
          cache: yarn
      - run: yarn install --frozen-lockfile --check-files
      - name: Test Frontend
        run: yarn test:ci
